(define (problem robot-1)
	(:domain sim)
	(:init 
		(leftHandEmptySensor)
		(rightHandEmptySensor)
		(operationalSensor)
		(viseEmptySensor)
		(= (sprayerHandSensor) 0)
		(= (sanderHandSensor) 0)
		(= (boardHandSensor) 0)
		(= (costs) 0)
	)
	(:goal (and (boardSandedSensor) (selfPaintedSensor)))
	(:metric minimize (costs))
)
